all: main
 
main: main.cpp controller.cpp controller.hpp help.cpp help.hpp menu.cpp menu.hpp Series.cpp Series.hpp SeriesDAO.hpp SeriesDAO.cpp ServerDBconnection.cpp ServerDBconnection.hpp sysinfo.cpp sysinfo.hpp
	g++ *.cpp -o main -lmariadbcpp